name: tour_guide
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  convex_bottom_bar: ^3.2.0
  animate_do:
  circle_nav_bar:
  carousel_slider:
  intl:
  supabase_flutter:
  shared_preferences:
  location:
  hive:
  hive_flutter:
  path_provider:
  build_runner:
  hive_generator:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/1.jpeg
    - assets/icons/2.jpeg
    - assets/icons/3.jpeg
    - assets/icons/4.jpeg
    - assets/icons/5.jpeg
    - assets/icons/6.jpeg
    - assets/icons/7.jpeg
    - assets/icons/8.jpg
    - assets/icons/
  fonts:
    - family: ArbFonts
      fonts:
        - asset: assets/fonts/alfont_com_Tasees-Regular.ttf